# Generated by Django 5.2.7 on 2025-11-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
