# Generated by Django 5.2.7 on 2025-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacy_app', '0002_delete_add_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpteryScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_uuid', models.CharField(max_length=255)),
                ('scan_id', models.CharField(max_length=255)),
                ('raw_scan_data', models.JSONField()),
                ('raw_screenshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
