# Generated by Django 5.2.7 on 2025-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpteryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday_day', models.IntegerField(blank=True, null=True)),
                ('birthday_month', models.IntegerField(blank=True, null=True)),
                ('birthday_year', models.IntegerField(blank=True, null=True)),
                ('plan', models.CharField(max_length=50)),
                ('postpone_scan', models.IntegerField(default=45)),
                ('group_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('optery_response', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Optery Member',
                'verbose_name_plural': 'Optery Members',
                'db_table': 'optery_members',
            },
        ),
    ]
