# Generated by Django 5.2.7 on 2025-11-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0004_opterymember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpteryMember',
        ),
    ]
