# Generated by Django 5.2.7 on 2025-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0006_opterymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opterymember',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
