# Generated by Django 5.2.7 on 2025-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0007_alter_opterymember_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opteryscanhistory',
            name='member_uuid',
        ),
        migrations.AddField(
            model_name='opteryscanhistory',
            name='email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
