# Generated by Django 5.2.7 on 2025-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0008_remove_opteryscanhistory_member_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opteryscanhistory',
            name='member_uuid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
