# Generated by Django 5.2.9 on 2026-01-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0009_opteryscanhistory_member_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opteryscanhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='opterymember',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='opteryscanhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='opteryscanhistory',
            name='email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opteryscanhistory',
            name='member_uuid',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opteryscanhistory',
            name='scan_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='opterymember',
            index=models.Index(fields=['email', 'created_at'], name='optery_memb_email_9afcac_idx'),
        ),
        migrations.AddIndex(
            model_name='opteryscanhistory',
            index=models.Index(fields=['member_uuid', 'email'], name='privacy_app_member__d2cf54_idx'),
        ),
        migrations.AddIndex(
            model_name='opteryscanhistory',
            index=models.Index(fields=['email', 'created_at'], name='privacy_app_email_d6b867_idx'),
        ),
    ]
