# Generated by Django 5.2.7 on 2025-10-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
        ),
    ]
