# Generated by Django 5.2.7 on 2025-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='short_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='subscription',
            name='limit',
            field=models.IntegerField(default=0, help_text='Usage limit for this plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='visibility_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
