# Generated by Django 5.2.7 on 2025-10-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_rename_short_description_subscription_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='visibility_type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
