# Generated by Django 5.2.7 on 2025-10-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0003_rename_description_subscription_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='features',
        ),
    ]
