# Generated by Django 5.2.7 on 2025-11-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0004_remove_subscription_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='short_description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
