# Generated by Django 5.2.7 on 2025-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0005_rename_short_description_subscription_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='features',
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.ManyToManyField(related_name='subscriptions', to='Subscriptions.feature'),
        ),
    ]
