# Generated by Django 5.2.7 on 2025-11-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0006_feature_remove_subscription_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
