# Generated by Django 5.2.9 on 2025-12-28 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0007_remove_feature_name_feature_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID for recurring payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for this subscription', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_subscription_id'], name='payments_stripe__b86ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='user_subscr_status_deb44c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at'], name='user_subscr_expires_e42bda_idx'),
        ),
    ]
