# Generated by Django 5.2.9 on 2026-01-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0008_payment_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelling', 'Cancelling (Will end at period)'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('payment_failed', 'Payment Failed'), ('payment_retrying', 'Payment Retrying')], default='active', max_length=20),
        ),
    ]
