"""
Django settings for AJAXX_Privacy_web project.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
Generated by 'django-admin startproject' using Django 5.2.7.
 
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
 
from pathlib import Path
import os
import environ
import redis
 
env = environ.Env()
 
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
 
 
CORS_ALLOW_ALL_ORIGINS = True
 
CORS_ALLOW_CREDENTIALS = True
 
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
 
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
 
# ✅ CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://10.10.10.46:8000',
    'https://backend.ajaxxdatascrubber.com',
    'https://www.ajaxxdatascrubber.com',
]
 
# ==================== SECRET KEY ====================
SECRET_KEY = env("SECRET_KEY")
 
DEBUG = True
 
ALLOWED_HOSTS = [
    'backend.ajaxxdatascrubber.com',
    'www.ajaxxdatascrubber.com',
    'ajaxxdatascrubber.com',
    '74.208.158.27',
    'localhost',
    '127.0.0.1',
    '10.10.10.46',
]

# CSRF_COOKIE_DOMAIN = '.ajaxxdatascrubber.com'
# SESSION_COOKIE_DOMAIN = '.ajaxxdatascrubber.com'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
AUTH_USER_MODEL = "Account.User"
 
# ==================== INSTALLED APPS ====================
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
 
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_celery_results',
    'stripe',
 
    # Local apps
    'privacy_app',
    'Account',
    'service',
    'Subscriptions',
    'product',
]
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')  # ✅ Changed from 'django-db' to Redis

# ==================== CELERY CONFIGURATION (Database Backend) ====================
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache' 
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_RESULT_EXTENDED = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_TASK_TRACK_STARTED = True
# Recommended production-safe limits: shorter to avoid long-running tasks
# Main tasks should complete quickly; increase if you intentionally run long jobs.
CELERY_TASK_SOFT_TIME_LIMIT = 15 * 60  # 15 minutes
CELERY_TASK_TIME_LIMIT = 18 * 60  # 18 minutes (hard limit)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Redis Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/0',
    }
}

# ==================== MIDDLEWARE ====================
 
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'AJAXX_Privacy_web.urls'
 
# ==================== REST FRAMEWORK ====================
 
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}
 
# ==================== JWT ====================
from datetime import timedelta
 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=20),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}
 
# ==================== TEMPLATES & WSGI ====================
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'AJAXX_Privacy_web.wsgi.application'
 
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 
 
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
# TIME_ZONE = 'UTC'
 
TIME_ZONE = 'America/New_York'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
 
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
 
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = env("EMAIL")
EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = "craigcrisp@ajaxxdatascrubber.com"
 
 
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"
 
 
# Stripe settings
STRIPE_LIVE_MODE = True
STRIPE_SECRET_KEY = env('stripe_secret_key')
STRIPE_PUBLISHABLE_KEY = env('stripe_publishable_key')
STRIPE_WEBHOOK_SECRET = env('stripe_webhook_secret')
 
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000')
 
 
OPTERY_INTEGRATION_UUID = env('OPTERY_INTEGRATION_UUID')
 
# Optery API Configuration
OPTERY_BASE_URL = os.getenv('OPTERY_BASE_URL')
OPTERY_API_KEY = os.getenv('OPTERY_API_TOKEN')
 
GOOGLE_CLIENT_ID= env("GOOGLE_CLIENT_ID")